[project]
name = "docx-comments-to-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-docx",
    "lxml",
    "click",
    "pytest>=8.4.1",
]
